### ISSUE TITLE
Add multiple user send suppoort

### ISSUE THREAD

**Issue by kevinfjiang** [kevinfjiang/FuncNotify#17]
### Requests 
> **You don't have to check off every box, although the more you can the easier it is on us**

* [X] Can you describe the feature?
* [X] Can you create a detailed roadmap of the feature?
* [X] Is it similar to any other repositories/projects?
* [ ] Is it similar to any other requests, open or closed?
* [ ] Would you be willing to contribute? 😊 

For more information, see the `CONTRIBUTING` guide.

### Description

Be able to send a message to multiple users, perferably by passing in a list or something

### Roadmap

1. Change `NotifyMethods.py` to support multiple recipients, some how allow it to recognize it'll send to multiple people
2. Change template.env

**Why this feature:** Might be nice

**Similar features:** [Links to features, Optional]

**Contact Info:** N/a

**Comment by DharaniDJ** [comment]
Hi @kevinfjiang , just to clarify, by "send a message to multiple users," do you specifically mean sending text messages via Twilio, or should this apply to all notification methods (Slack, Email, Teams, etc.)?

**Comment by kevinfjiang** [comment]
Primarily multiple users, so notifying multiple people after a function concludes

**Comment by Sameer-Pal** [comment]
is this still open ?
